[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dbt-column-lineage-extractor"
version = "0.2.3"
description = "A package for extracting dbt column lineage"
readme = "readme.md"
requires-python = ">=3.12"
authors = [
    { name = "Wen Wu", email = "wenwu@canva.com" },
    { name = "Benjamin Allévius", email = "benjamin.allevius@shopify.com" }
]
dependencies = [
    "sqlglot[rs]>=26.29.0",
]

[project.urls]
"Homepage" = "https://github.com/canva-public/dbt-column-lineage-extractor"

[project.scripts]
dbt_column_lineage_direct = "dbt_column_lineage_extractor.cli_direct:main"
dbt_column_lineage_recursive = "dbt_column_lineage_extractor.cli_recursive:main"
dbt_column_lineage_root_sources = "dbt_column_lineage_extractor.cli_root_sources:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.0",
]
